---
- stat: path=/opt/jdk-8u112-linux-x64.tar.gz
  register: jdk_installer

- shell:
    "curl -L  -H 'Cookie:oraclelicense=accept-securebackup-cookie' -o /opt/jdk-8u112-linux-x64.tar.gz http://download.oracle.com/otn-pub/java/jdk/8u112-b15/jdk-8u112-linux-x64.tar.gz"
  when: not jdk_installer.stat.exists
  environment: "{{proxy_env}}"

- stat: path=/opt/jdk1.8.0_112
  register: jdk_dir

- unarchive: src=/opt/jdk-8u112-linux-x64.tar.gz dest=/opt remote_src=yes
  when: not jdk_dir.stat.exists
