---
driver:
  name: docker
  use_sudo: False

provisioner:
  name: ansible_playbook
  hosts: test-kitchen
  ansible_version: latest
  roles_path: roles

platforms:
  - name: ubuntu-16.04

suites:
  - name: vmprepare 
