- name: Create EC2 instance
  hosts: localhost
  gather_facts: False
  vars:
    key_name: my_keypair
    instance_type: m1.small
    security_group: my_securitygroup
    image: my_ami_id #
    region: eu-east-1
  tasks:
    - name: Launch a instance # count: default 1
      ec2:
         key_name: "{{ key_name }}"
         group: "{{ security_group }}"
         instance_type: "{{ instance_type }}"
         image: "{{ image }}"
         wait: true
         region: "{{ region }}"
         vpc_subnet_id: subnet-1
         assign_public_ip: yes
      register: ec2

    - name: Add the new instance to host group
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: launched
      with_items: "{{ ec2.instances }}"

    - name: Wait for SSH
      wait_for:
        host: "{{ item.public_dns_name }}"
        port: 22
        delay: 60
        timeout: 300
        state: started
      with_items: "{{ ec2.instances }}"

- name: Deploy and test
  hosts: launched
  vars:
    repo_url: https://github.com/IronCore864/devops
    repo_version: master
    webapps_dir: /var/www/
  become: True
  gather_facts: True
  tasks:
  - name: pull
    git: repo={{repo_url}} dest={{webapps_dir}} version={{repo_version}}
  - shell: "cd {{webapps_dir}} && python app.py &"
  - shell: "cd {{webapps_dir}} && python test.py >test_result.txt 2>&1"
  - shell: "mail -s "Hello World" user@domain.com < /var/www/test_result.txt"

- name: Terminate
  hosts: localhost
  connection: local
  tasks:
    - name: Terminate the instance that were previously launched
      ec2:
        state: 'absent'
        instance_ids: '{{ ec2.instance_ids }}'

