version: 2
jobs:
  build:
    machine:
      image: circleci/classic:latest
      services:
        - docker
      ruby:
        version: 2.4.0

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            bundle install

      - run:
          name: run tests
          command: |
            kitchen test

