version: 2
jobs:
  build:
    machine:
      image: circleci/classic:latest
      services:
        - docker
      ruby:
        version: 2.4.0

    working_directory: ~/repo

    steps:
      - checkout

#      - restore_cache:
#          keys:
#          - v1-dependencies-{{ checksum "Gemfile.lock" }}
#          # fallback to using the latest cache if no exact match is found
#          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

#      - save_cache:
#          paths:
#            - ./vendor/bundle
#          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      - run:
          name: ls -l
          command: |
            ls -l vendor/bundle/ruby/2.4.0/gems/test-kitchen*/bin

      - run:
          name: ls -l
          command: |
            ls -l /opt/circleci/.rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems
        
      - run:
          name: run tests
          command: |
            vendor/bundle/ruby/2.4.0/gems/test-kitchen*/bin/kitchen test

