---
- name: Ensure reallocate installation and configuration directories exist.
  file:
    path: "{{ item }}"
    state: directory
    owner: "eas2"
    group: "as2"
    mode: 0750
  with_items:
    - "{{ install_dir }}"
    - "{{ config_dir }}"
