---

- name: Ensures that /usr/bin/ksh exists
  file: 
    src: /bin/ksh
    dest: /usr/bin/ksh
    owner: root
    group: root
    state: link

- name: Ensures all dependency dirs exist
  file:
    path: "{{ item }}"
    recurse: yes
    state: directory
    owner: "eas2"
    group: "as2"
    mode: 0750
  with_items:
    - "/ib/lib/ksh"
    - "/ib/sw"
    - "/ib/etc/codes"
    - "/ib/sem"
    - "{{ tosend_dir }}"

- name: Copy some env files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "eas2"
    group: "as2"
    mode: 0640
  items:
    - { src: ".as2env", dest: "/ib/.as2env" }
    - { src: "exitCodes.dat", dest: "/ib/etc/codes/exitCodes.dat" }

- name: Download dependencies for reallocate
  unarchive:
    src: "http://dehamsl1806.int.kn/ansible/artifacts/reallocate/{{ item.pack }}"
    remote_src: yes
    owner: eas2
    group: as2
    dest: "{{ item.dest }}"
  items:
    - { pack: "env.tar.gz", dest: "/ib/lib/ksh" }
    - { pack: "ediscripts.tar.gz", dest: "/ib/sw" }

- name: Update permission of the folders
  file:
    path: "{{ item }}"
    recurse: yes
    mode: u=rwX,g=rX
  items:
    - "/ib/lib/ksh/env"
    - "/ib/sw/ediscripts"

- name: Ensures crontab log dir exists
  file:
    path: "{{ cron_log_dir }}"
    state: directory
    owner: "eas2"
    group: "as2"
    mode: 0755

