---
- include: dependencies.yml

- name: Disable reallocate cron job before installing
  cron:
    name: "eas2 reallocate {{ item }}"
    user: "eas2"
    job: "{{ install_dir }}/reallocate.ctb {{ item }} /ib/mbin/EDI_EAS2/cfg 2>&1 | /ib/sw/ediscripts/logToEdistart.pl {{ cron_log_dir }}/log"
    state: absent
  with_items: "{{ EAS2_REALLOCATE_INSTANCES }}"

- name: Copy reallocate script
  copy:
    src: "reallocate.ctb"
    dest: "{{ install_dir }}/reallocate.ctb"
    owner: "eas2"
    group: "as2"
    mode: 0755

