---
- name: Ensure as2 dir exists.
  file:
    path: /as2
    state: directory
    owner: "eas2"
    group: "as2"
    mode: 0755

- name: Ensure eas2 user home dir exists.
  file:
    path: /as2/eas2
    state: directory
    owner: "eas2"
    group: "as2"
    mode: 0755

- name: Ensure ib dir exists.
  file:
    path: /ib
    state: directory
    owner: "eas2"
    group: "as2"
    mode: 0775

- name: Ensure as2log dir exists.
  file:
    path: /as2log
    state: directory
    owner: "eas2"
    group: "as2"
    mode: 0775

- name: Ensure JAVA_HOME exists.
  file:
    path: "{{ JAVA_HOME }}"
    state: directory
    owner: "root"
    group: "root"
    mode: 0775

- name: Ensure java security config file exists.
  file:
    path: "{{ JAVA_HOME }}/jre/lib/security/java.security"
    state: file
    owner: "root"
    group: "root"
    mode: 0644

- name: update java params
  lineinfile:
    dest: "{{ JAVA_HOME }}/jre/lib/security/java.security"
    regexp: '^jdk\.certpath\.disabledAlgorithms'
    line: "jdk.certpath.disabledAlgorithms=MD2, RSA keySize < 1024"
    state: present

- name: update java params
  lineinfile:
    dest: "{{ JAVA_HOME }}/jre/lib/security/java.security"
    regexp: '^jdk\.tls\.disabledAlgorithms'
    line: "jdk.tls.disabledAlgorithms=SSLv2"
    state: present

