---

- name: Ensure database exists
  mysql_db:
    name: "{{ db_name }}"
    login_host: "{{ db_host }}"
    login_user: "{{ db_user }}"
    login_password: "{{ db_password }}"
    state: present
  register: db

- name: ensure DB schema is generated after first install
  mysql_db:
    name: "{{ db_name }}"
    login_host: "{{ db_host }}"
    login_user: "{{ db_user }}"
    login_password: "{{ db_password }}"
    state: import
    target: "{{ mysql_script_dir }}/eas2.sql"
  when: db.changed

- name: Ensure dbupdate script exsits
  copy:
    src: dbupdate.ksh
    dest: "{{ mysql_script_dir }}/dbupdate.ksh"
    owner: "{{ FILE_OWNER }}"
    group: "{{ FILE_GROUP }}"
    mode: "{{ FILE_MODE_EXECUTE }}"

- name: Ensure DB is up to date
  shell: "cd {{ mysql_script_dir }} && ./dbupdate.ksh -s {{ db_host }} -u {{ db_user }} -d {{ db_name }} -p {{ db_password }}"

