---
- name: Ensure e-AS2 server is started
  become_user: eas2
  shell: "{{ restart_eas2 }}"

- name: Check if EAS2.properties contains healthcheck port
  shell: "grep connection.healthcheck.port {{ HOME_DIR }}/e-AS2/EAS2.properties"
  register: healthcheck
  ignore_errors: True

- name: Check health check port is being listened
  wait_for:
    port: "{{ hc_port }}"
    delay: 5
    timeout: 45
  when: healthcheck|succeeded

- name: Enable crontab job
  cron:
    name: "{{ cron_name }}"
    user: "eas2"
    minute: "{{ cron_minute }}"
    job: "{{ cron_job }}"

