---
- name: Ensure eas2ud install directory exists.
  file:
    path={{ INSTALL_HOME_DIR }}
    state=directory
    owner="eas2"
    group="as2"
    mode=0755

- name: Ensure as2log directory exists.
  file:
    path=/as2log
    state=directory
    owner="eas2"
    group="as2"
    mode=0775

- set_fact:
    cron_taskname: "Disable crontab job for EAS2UD service restarting"
    cron_off: true
- include: crontab.yml

- stat:
    path: "{{ INSTALL_HOME_DIR }}/{{ DIR_NAME }}-{{ VERSION }}"
  register: p

- name: "Starting an installation of {{ VERSION }} version"
  include: install.yml
  when: p.stat.isdir is not defined

- set_fact:
    new_version: "{{ INSTALL_HOME_DIR }}/{{ DIR_NAME }}-{{ VERSION }}"

- stat:
    path: "{{ INSTALL_HOME_DIR }}/{{ DIR_NAME }}"
  register: active

- include: activate.yml
  when: active.stat.islnk and active.stat.lnk_source != new_version

- include: configure.yml

- include: sshkeys.yml
  when: ADD_SSH_AUTH

- set_fact:
    cron_taskname: "Enable crontab job for EAS2UD service restarting"
    cron_off: false
- include: crontab.yml
