---

- name: Download private/public keys
  unarchive:
    src: "http://dehamsl1806.int.kn/ansible/artifacts/eas2ud/{{ SSHKEYS }}"
    remote_src: yes
    dest: "{{ HOME_DIR }}"
    owner: "eas2"
    group: "as2"

- name: Set proper permissions to .ssh folder
  file:
    path: "{{ HOME_DIR }}/.ssh"
    state: directory
    owner: "eas2"
    group: "as2"
    mode: 0700

- name: Set proper permission to the all of keys
  file:
    path: "{{ HOME_DIR }}/.ssh/{{ item.file }}"
    state: file
    owner: "eas2"
    group: "as2"
    mode: "{{ item.mode }}"
  with_items:
    - { file: "id_rsa", mode: "0600" }
    - { file: "id_rsa.pub", mode: "0640" }
    - { file: "known_hosts", mode: "0644" }
    - { file: "authorized_keys", mode: "0640" }
