---
- hosts: dehamsp20
  tasks:
    - shell: "sleep 30 && {{ item }}"
      with_items:
        - "echo 1"
        - "echo 2"
        - "grep a b"
      register: r
      async: 30 
      poll: 5
      ignore_errors: yes

    - debug:
        msg: "{{ item.stdout }}"
      with_items: "{{ r.results }}"
