---
- name: Download logstash-forwarder-java from github source
  command: "wget {{download_url}} -O {{archive_file_name}}"

# unzip downloaded installer
- unarchive: src={{archive_file_name}} dest={{install_dir}} remote_src=yes copy=no

# check if it is unzipped correctly
- stat: path={{install_dir}}/{{dir_name}}
  register: p

- debug: msg="logstash-forwarder-java is already unpacked"
  when: p.stat.isdir is defined and p.stat.isdir

# remove downloaded zip file
- file: path={{archive_file_name}} state=absent

- name: Copy logstash-forwarder-java configuration.
  template:
    src: logstash-forwarder-config.json.j2
    dest: "{{install_dir}}/{{dir_name}}/logstash-forwarder-config.json"
    owner: edi 
    group: edi  
    mode: 0664

- name: Create logstash-forwarder-java local cache file.
  copy:
    src: logstash-forwarder-java
    dest: "{{install_dir}}/{{dir_name}}/.logstash-forwarder-java"
    owner: edi
    group: edi
    mode: 0664

- name: Copy logstash-forwarder-java key.
  copy:
    src: logstash-forwarder.jks
    dest: "{{install_dir}}/{{dir_name}}/logstash-forwarder.jks"
    owner: edi
    group: edi
    mode: 0640

- name: Copy logstash-forwarder-java keystore.
  copy:
    src: keystore.jks
    dest: "{{install_dir}}/{{dir_name}}/keystore.jks"
    owner: edi
    group: edi
    mode: 0640

- name: Copy logstash-forwarder-java service file so that you can use edistart/stop to control it.
  copy:
    src: LOGSTASH_FORWARDER_SRV
    dest: "{{srv_file_dir}}/LOGSTASH_FORWARDER_SRV"
    owner: edi
    group: edi
    mode: 0664

# Add service name into .edistat file so that you can use edistart/stop/stat with logstash forwarder
- lineinfile: dest={{ edistat_file }} line={{ srv_name }} state=present
